# config/filter/featured-image.filter.yaml
services:
    featured_image.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [{ id: exact, pageType: : exact }]
        tags: ['api_platform.filter']
    featured_image.order_filter:
        parent: 'api_platform.doctrine.orm.order_filter'
        arguments: [{ id: 'ASC', sortOrder: 'ASC' }]
        tags: ['api_platform.filter']