# config/filter/place-image.filter.yaml
services:
    place_image.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [{ place.id: exact, countryCode: exact, regionCode: exact }]
        tags: ['api_platform.filter']
    place_image.order_filter:
        parent: 'api_platform.doctrine.orm.order_filter'
        arguments: [{ id: 'ASC', sortOrder: 'ASC' }]
        tags: ['api_platform.filter']
