# config/filter/region.filter.yaml
services:
    region.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [{ regionName: 'partial' }]
        tags:  [ 'api_platform.filter' ]
    region.order_filter:
        parent: 'api_platform.doctrine.orm.order_filter'
        arguments: [{ regionCode: 'ASC', regionName: 'ASC', sortOrder: 'ASC' }]
        tags: ['api_platform.filter']