# config/filter/user.filter.yaml
services:
    user.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [{
            name: 'partial',
            email: 'partial',
            firstName: 'partial',
            lastName: 'partial',
            middleName: 'partial',
        }]
        tags:  [ 'api_platform.filter' ]
    user.order_filter:
        parent: 'api_platform.doctrine.orm.order_filter'
        arguments: [{
            name: 'ASC',
            email: 'ASC',
            userId: 'ASC',
            status: 'ASC',
            createdAt: 'ASC',
            updatedAt: 'ASC',
        }]
        tags: ['api_platform.filter']